Notes Meeting 29042021
fricklerhandwerk/ranim pull request #14
Opened 2021-04-29 09:58 UTC by Bo016

I worte some notes during the Meeting. Please complete those with your own (if existing) so that we dont forget the feedback or ideas.

2021-04-29 10:27 UTC, timgrewe approved these changes
This is just about what I also took away from the meeting.

2021-04-29 12:06 UTC, fricklerhandwerk requested changes
Translated to English and added notes on why/how to do hand-eye-calibration and how to drive the actual robot.

2021-04-29 12:14 UTC, fricklerhandwerk commented on MeetingGerlach29042021.txt
> +andere ROS nodes bitte nicht
I also suggest to rename the file using [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) dates and to use [markdown](https://en.wikipedia.org/wiki/Markdown) for plain text documents generally: `2021-04-29 tutor meeting notes.md`.
ISO dates are unambiguous, sortable and (in my opinion) still easy to read. Markdown conveys a bit of structure while still being plain text, and can be nicely converted to other document types such as PDF or HTML when needed.

2021-04-29 13:08 UTC, timgrewe commented on MeetingGerlach29042021.txt
> +andere ROS nodes bitte nicht
I absolutely agree on the date formatting.

2021-04-29 13:08 UTC, timgrewe approved these changes

2021-04-30 14:12 UTC, tobiastuhh approved these changes
looks good

2021-05-01 18:23 UTC, fricklerhandwerk approved these changes

2021-05-01 18:24 UTC, merged